### PR TITLE
Update monaco-editor to version 0.34.0

### PR DESCRIPTION
**Pull request by Urook**

### CODE REVIEW

**Comment by Urook** [comment]
@suren-atoyan Is this PR ok by you? (GitHub does not let me add you as a reviewer for some reason)

**Comment by suren-atoyan** [comment]
hey @Urook, yes, it looks good - I'll merge it now, but it will take some time to publish it

**Comment by suren-atoyan** [comment]
@Urook also, be aware that you can always choose the exact version you need by using [config](https://github.com/suren-atoyan/monaco-loader#config):

```js

import loader from '@monaco-editor/loader';

loader.config({ paths: { vs: 'https://cdn.jsdelivr.net/npm/monaco-editor@0.34.0/min/vs' } });
```

**Comment by Urook** [comment]
Thank you :)

**Pull request merged**
