### PR TITLE
upgrade monaco-editor version to 0.43.0

### PR DESCRIPTION
**Pull request by jgoux**
To use the latest published version of monaco-editor. 👍 

Once merged, could you do a new release? 🙏

So we can then upgrade `@monaco-editor/react` dependencies to this version 👆 and enjoy TypeScript v5 with it. 😄

### CODE REVIEW

**Comment by Urook** [comment]
@suren-atoyan +1 May this please be done? :)

**Comment by suren-atoyan** [comment]
@jgoux @Urook I'll let you know once I release the new version. But please note that you can always load a different monaco version by using [the config](https://github.com/suren-atoyan/monaco-loader#config):

```js
import loader from '@monaco-editor/loader';

loader.config({ paths: { vs: 'https://cdn.jsdelivr.net/npm/monaco-editor@0.43.0/min/vs' } });
```

**Comment by Urook** [comment]
@suren-atoyan Is it possible to update @monaco-editor/react with this new package after it is released?

**Comment by suren-atoyan** [comment]
this is publish 🙂 check the latest version

**Pull request merged**
